export const SHOW_FORM_LOGIN = "SHOW_FORM_LOGIN";
export const CLOSE_FORM_LOGIN = "CLOSE_FORM_LOGIN";
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const SET_ERROR_LOGIN = "SET_ERROR_LOGIN"
export const CLEAR_ERROR_LOGIN = "CLEAR_ERROR_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";

export const SHOW_FORM_REGISTER = "SHOW_FORM_REGISTER";
export const CLOSE_FORM_REGISTER = "CLOSE_FORM_REGISTER";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const SET_ERROR_REGISTER = "SET_ERROR_REGISTER";
export const CLEAR_ERROR_REGISTER = "CLEAR_ERROR_REGISTER";
export const REMOVE_ERROR_REGISTER = "REMOVE_ERROR_REGISTER";

export const SHOW_FORM_FORGOT = "SHOW_FORM_FORGOT";
export const CLOSE_FORM_FORGOT = "CLOSE_FORM_FORGOT";
export const SEND_FORGOT_REQUEST = "SEND_FORGOT_REQUEST";
export const SEND_FORGOT_SUCCESS = "SEND_FORGOT_SUCCESS";
export const SEND_FORGOT_FAIL = "SEND_FORGOT_FAIL";
