export const ADD_CART_REQUEST = "ADD_CART_REQUEST"
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS"
export const ADD_CART_FAIL = "ADD_CART_FAIL"

export const GET_LIST_CART_REQUEST = "GET_LIST_CART_REQUEST"
export const GET_LIST_CART_SUCCESS = "GET_LIST_CART_SUCCESS"
export const GET_LIST_CART_FAIL = "GET_LIST_CART_FAIL"

export const UPDATE_SELECTED_REQUEST = "UPDATE_SELECTED_REQUEST"
export const UPDATE_SELECTED_SUCCESS = "UPDATE_SELECTED_SUCCESS"
export const UPDATE_SELECTED_FAIL = "UPDATE_SELECTED_FAIL"

export const REMOVE_ITEM_CART_REQUEST = "REMOVE_ITEM_CART_REQUEST"
export const REMOVE_ITEM_CART_SUCCESS = "REMOVE_ITEM_CART_SUCCESS"
export const REMOVE_ITEM_CART_FAIL = "REMOVE_ITEM_CART_FAIL"

export const UPDATE_QUANTITY_REQUEST = "UPDATE_QUANTITY_REQUEST"
export const UPDATE_QUANTITY_SUCCESS = "UPDATE_QUANTITY_SUCCESS"
export const UPDATE_QUANTITY_FAIL = "UPDATE_QUANTITY_FAIL"