export const GET_LIST_CERTIFIED_REQUEST = "GET_LIST_CERTIFIED_REQUEST"
export const GET_LIST_CERTIFIED_SUCCESS = "GET_LIST_CERTIFIED_SUCCESS"
export const GET_LIST_CERTIFIED_FAIL = "GET_LIST_CERTIFIED_FAIL"