export const SHOW_CONTACT = "SHOW_CONTACT";
export const CLOSE_CONTACT = "CLOSE_CONTACT";

export const SEND_CONTACT_REQUEST = "SEND_CONTACT_REQUEST";
export const SEND_CONTACT_SUCCESS = "SEND_CONTACT_SUCCESS";
export const SEND_CONTACT_FAIL = "SEND_CONTACT_FAIL";