export const UPDATE_CONTENT = "UPDATE_CONTENT"
export const UPDATE_NUMBER_STAR = "UPDATE_NUMBER_STAR"

export const GET_FEEDBACK_PUBLIC_REQUEST = "GET_FEEDBACK_PUBLIC_REQUEST"
export const GET_FEEDBACK_PUBLIC_SUCCESS = "GET_FEEDBACK_PUBLIC_SUCCESS"
export const GET_FEEDBACK_PUBLIC_FAIL = "GET_FEEDBACK_PUBLIC_FAIL"

export const CREATE_FEEDBACK_PUBLIC_REQUEST = "CREATE_FEEDBACK_PUBLIC_REQUEST"
export const CREATE_FEEDBACK_PUBLIC_SUCCESS = "CREATE_FEEDBACK_PUBLIC_SUCCESS"
export const CREATE_FEEDBACK_PUBLIC_FAIL = "CREATE_FEEDBACK_PUBLIC_FAIL"

// Feedback Private
export const SET_TYPE_FEEL = "SET_TYPE_FEEL"
export const ADD_FAST_ANS = "ADD_FAST_ANS"
export const REMOVE_FAST_ANS = "REMOVE_FAST_ANS"
export const RESET_TYPE_FEEL = "RESET_TYPE_FEEL"
export const ADD_CONTENT_ANS = "ADD_CONTENT_ANS"