export const GET_INFO_USER_REQUEST = 'GET_INFO_USER_REQUEST';
export const GET_INFO_USER_SUCCESS = 'GET_INFO_USER_SUCCESS';
export const GET_INFO_USER_FAIL = 'GET_INFO_USER_FAIL';

export const UPDATE_INFO_USER_REQUEST = 'UPDATE_INFO_USER_REQUEST';
export const UPDATE_INFO_USER_SUCCESS = 'UPDATE_INFO_USER_SUCCESS';
export const UPDATE_INFO_USER_FAIL = 'UPDATE_INFO_USER_FAIL';

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL';

export const GET_SUGGEST_ADDRESS_REQUEST = 'GET_SUGGEST_ADDRESS_REQUEST';
export const GET_SUGGEST_ADDRESS_SUCCESS = 'GET_SUGGEST_ADDRESS_SUCCESS';
export const GET_SUGGEST_ADDRESS_FAIL = 'GET_SUGGEST_ADDRESS_FAIL';