export const GET_LIST_NEWS_REQUEST = "GET_LIST_NEWS_REQUEST"
export const GET_LIST_NEWS_SUCCESS = "GET_LIST_NEWS_SUCCESS"
export const GET_LIST_NEWS_FAIL = "GET_LIST_NEWS_FAIL"

export const GET_DETAIL_NEWS_REQUEST = "GET_DETAIL_NEWS_REQUEST"
export const GET_DETAIL_NEWS_SUCCESS = "GET_DETAIL_NEWS_SUCCESS"
export const GET_DETAIL_NEWS_FAIL = "GET_DETAIL_NEWS_FAIL"