export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL"
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET"

export const GET_ORDER_WAITING_REQUEST = "GET_ORDER_WAITING_REQUEST"
export const GET_ORDER_WAITING_SUCCESS = "GET_ORDER_WAITING_SUCCESS"
export const GET_ORDER_WAITING_FAIL = "GET_ORDER_WAITING_FAIL"

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST"
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS"
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL"
export const ORDER_PAY_RESET = "ORDER_PAY_RESET"

export const RE_ORDER_REQUEST = "RE_ORDER_REQUEST"
export const RE_ORDER_SUCCESS = "RE_ORDER_SUCCESS"
export const RE_ORDER_FAIL = "RE_ORDER_FAIL"
export const RE_ORDER_RESET = "RE_ORDER_RESET"