export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_TYPE_REQUEST = "PRODUCT_TYPE_REQUEST";
export const PRODUCT_TYPE_SUCCESS = "PRODUCT_TYPE_SUCCESS";
export const PRODUCT_TYPE_FAIL = "PRODUCT_TYPE_FAIL";

export const GET_INFO_PRODUCT_REQUEST = "GET_INFO_PRODUCT_REQUEST";
export const GET_INFO_PRODUCT_SUCCESS = "GET_INFO_PRODUCT_SUCCESS";
export const GET_INFO_PRODUCT_FAIL = "GET_INFO_PRODUCT_FAIL";