export const GET_LIST_PURCHASE_REQUEST = "GET_LIST_PURCHASE_REQUEST"
export const GET_LIST_PURCHASE_SUCCESS = "GET_LIST_PURCHASE_SUCCESS"
export const GET_LIST_PURCHASE_FAIL = "GET_LIST_PURCHASE_FAIL"

export const CANCEL_PURCHASE_REQUEST = "CANCEL_PURCHASE_REQUEST"
export const CANCEL_PURCHASE_SUCCESS = "CANCEL_PURCHASE_SUCCESS"
export const CANCEL_PURCHASE_FAIL = "CANCEL_PURCHASE_FAIL"
export const RESET_CANCEL_PURCHASE = "RESET_CANCEL_PURCHASE"

export const FEEDBACK_PURCHASE_REQUEST = "FEEDBACK_PURCHASE_REQUEST"
export const FEEDBACK_PURCHASE_SUCCESS = "FEEDBACK_PURCHASE_SUCCESS"
export const FEEDBACK_PURCHASE_FAIL = "FEEDBACK_PURCHASE_FAIL"
export const RESET_FEEDBACK_PURCHASE = "RESET_FEEDBACK_PURCHASE"

export const UPDATE_LIST_PURCHASE = "UPDATE_LIST_PURCHASE"